# .goreleaser.yml
# Build customization
builds:
  - binary: jumper
    main: ./jumper/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    flags:
      - -trimpath
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
